development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: loan_management
  pool: 5
  username: postgres
  password: 12345
test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: loan_management
  pool: 5
  username: postgres
  password: 12345
