default: &default
  adapter: postgresql
  username: postgres
  password: 12345
  pool: 15
  timeout: 5000
  host: localhost

development:
  <<: *default
  database: loan-app-dev

test:
  <<: *default
  database: loan-app-test

production:
  <<: *default
  database: loan-app-production